export const BLACK_COLOR = '#172d3d'
export const BLACK_LIGHT_COLOR = '#324559'
export const DARK_GREY_COLOR = '#6b7983'
export const INACTIVE_GREY_COLOR = '#92969c'
export const LIGHT_GREY_COLOR = '#eef2f5'
export const WHITE_COLOR = '#ffffff'

export const PRIMARY_COLOR = '#f16a54'
export const PRIMARY_DARK_COLOR = '#b54e3d'
export const SECONDARY_COLOR = '#60E0CC'
export const SECONDARY_DARK_COLOR = '#3e9385'
export const TERTIARY_COLOR = '#7252cf'
export const TERTIARY_DARK_COLOR = '#453082'
